name: Update readme

on: 
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
        
    - name: Run update.py
      run: |
        python update.py
        
    - name: Commit changes
      run: |
        git config --global user.name 'j00boy'
        git config --global user.email 'kkjjhh9705@gmail.com'
        git add -A
        git commit -am "auto update README.md"
        
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/j00boy/APS.git
        git push origin main
